import * as vscode from 'vscode';
import { lerpColor } from '../utils/colors';

// ── Palette definitions ──────────────────────────────────────────────────────

export interface Palette {
  name: string;
  type: 'dark' | 'light';
  indicator: string;
  accent: string;
  /** Gradient stops for the card preview (start → mid → end) */
  preview: [string, string, string];
  colors: Record<string, string>;
}

export const PALETTES: Palette[] = [

  // ── DARK palettes ───────────────────────────────────────────
  {
    name: 'Neon Green', type: 'dark', indicator: 'G', accent: '#00ff88',
    preview: ['#091a0d', '#00cc6a', '#00ff88'],
    colors: {
      'titleBar.activeBackground':        '#091a0d',
      'titleBar.activeForeground':        '#00ff88',
      'titleBar.inactiveBackground':      '#061008',
      'titleBar.inactiveForeground':      '#3dcc77',
      'titleBar.border':                  '#00cc6a',
      'activityBar.background':           '#091a0d',
      'activityBar.foreground':           '#00ff88',
      'activityBar.inactiveForeground':   '#1a6640',
      'activityBar.border':               '#00aa55',
      'activityBarBadge.background':      '#00ff88',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#003d1f',
      'statusBar.foreground':             '#00ff88',
      'statusBar.border':                 '#00cc6a',
      'statusBarItem.hoverBackground':    '#005c2e',
      'sideBar.background':               '#0b1f0e',
      'sideBar.foreground':               '#b8ffcc',
      'sideBar.border':                   '#00aa55',
      'sideBarTitle.foreground':          '#00ff88',
      'sideBarSectionHeader.background':  '#062610',
      'sideBarSectionHeader.foreground':  '#00ff88',
      'editorGroupHeader.tabsBackground': '#091a0d',
      'tab.activeBackground':             '#153d1e',
      'tab.activeForeground':             '#00ff88',
      'tab.activeBorder':                 '#00ff88',
      'tab.inactiveBackground':           '#0b1f0e',
      'tab.inactiveForeground':           '#3d8057',
      'focusBorder':                      '#00ff88',
      'selection.background':             '#00ff8833',
      'menu.background':                  '#0b1f0e',
      'menu.foreground':                  '#b8ffcc',
      'menu.selectionBackground':         '#003d1f',
      'menu.selectionForeground':         '#00ff88',
      'menubar.selectionBackground':      '#003d1f',
      'menubar.selectionForeground':      '#00ff88',
      'panel.background':                 '#0b1f0e',
      'panel.border':                     '#00aa55',
      'panelTitle.activeForeground':      '#00ff88',
      'panelTitle.activeBorder':          '#00ff88',
      'scrollbarSlider.background':       '#00ff8830',
      'scrollbarSlider.hoverBackground':  '#00ff8855',
    },
  },

  {
    name: 'Neon Blue', type: 'dark', indicator: 'B', accent: '#00d4ff',
    preview: ['#081220', '#0099cc', '#00d4ff'],
    colors: {
      'titleBar.activeBackground':        '#081220',
      'titleBar.activeForeground':        '#00d4ff',
      'titleBar.inactiveBackground':      '#050c18',
      'titleBar.inactiveForeground':      '#3dbfee',
      'titleBar.border':                  '#0099cc',
      'activityBar.background':           '#081220',
      'activityBar.foreground':           '#00d4ff',
      'activityBar.inactiveForeground':   '#194d66',
      'activityBar.border':               '#0088bb',
      'activityBarBadge.background':      '#00d4ff',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#003348',
      'statusBar.foreground':             '#00d4ff',
      'statusBar.border':                 '#0099cc',
      'statusBarItem.hoverBackground':    '#004c6e',
      'sideBar.background':               '#091525',
      'sideBar.foreground':               '#b0e8ff',
      'sideBar.border':                   '#0088bb',
      'sideBarTitle.foreground':          '#00d4ff',
      'sideBarSectionHeader.background':  '#051020',
      'sideBarSectionHeader.foreground':  '#00d4ff',
      'editorGroupHeader.tabsBackground': '#081220',
      'tab.activeBackground':             '#112d40',
      'tab.activeForeground':             '#00d4ff',
      'tab.activeBorder':                 '#00d4ff',
      'tab.inactiveBackground':           '#091525',
      'tab.inactiveForeground':           '#3d7d99',
      'focusBorder':                      '#00d4ff',
      'selection.background':             '#00d4ff33',
      'menu.background':                  '#091525',
      'menu.foreground':                  '#b0e8ff',
      'menu.selectionBackground':         '#003348',
      'menu.selectionForeground':         '#00d4ff',
      'menubar.selectionBackground':      '#003348',
      'menubar.selectionForeground':      '#00d4ff',
      'panel.background':                 '#091525',
      'panel.border':                     '#0088bb',
      'panelTitle.activeForeground':      '#00d4ff',
      'panelTitle.activeBorder':          '#00d4ff',
      'scrollbarSlider.background':       '#00d4ff30',
      'scrollbarSlider.hoverBackground':  '#00d4ff55',
    },
  },

  {
    name: 'Dark Purple', type: 'dark', indicator: 'P', accent: '#c060ff',
    preview: ['#120a1f', '#8822bb', '#c060ff'],
    colors: {
      'titleBar.activeBackground':        '#120a1f',
      'titleBar.activeForeground':        '#c060ff',
      'titleBar.inactiveBackground':      '#0c0618',
      'titleBar.inactiveForeground':      '#9944cc',
      'titleBar.border':                  '#8822bb',
      'activityBar.background':           '#120a1f',
      'activityBar.foreground':           '#c060ff',
      'activityBar.inactiveForeground':   '#4d1a6e',
      'activityBar.border':               '#8822bb',
      'activityBarBadge.background':      '#c060ff',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#2d0048',
      'statusBar.foreground':             '#c060ff',
      'statusBar.border':                 '#8822bb',
      'statusBarItem.hoverBackground':    '#44006e',
      'sideBar.background':               '#150c22',
      'sideBar.foreground':               '#e0c0ff',
      'sideBar.border':                   '#8822bb',
      'sideBarTitle.foreground':          '#c060ff',
      'sideBarSectionHeader.background':  '#0e0820',
      'sideBarSectionHeader.foreground':  '#c060ff',
      'editorGroupHeader.tabsBackground': '#120a1f',
      'tab.activeBackground':             '#271040',
      'tab.activeForeground':             '#c060ff',
      'tab.activeBorder':                 '#c060ff',
      'tab.inactiveBackground':           '#150c22',
      'tab.inactiveForeground':           '#7d3d99',
      'focusBorder':                      '#c060ff',
      'selection.background':             '#c060ff33',
      'menu.background':                  '#150c22',
      'menu.foreground':                  '#e0c0ff',
      'menu.selectionBackground':         '#2d0048',
      'menu.selectionForeground':         '#c060ff',
      'menubar.selectionBackground':      '#2d0048',
      'menubar.selectionForeground':      '#c060ff',
      'panel.background':                 '#150c22',
      'panel.border':                     '#8822bb',
      'panelTitle.activeForeground':      '#c060ff',
      'panelTitle.activeBorder':          '#c060ff',
      'scrollbarSlider.background':       '#c060ff30',
      'scrollbarSlider.hoverBackground':  '#c060ff55',
    },
  },

  // ── EXTRA DARK palettes ─────────────────────────────────────
  {
    name: 'Neon Orange', type: 'dark', indicator: 'NO', accent: '#ff6a00',
    preview: ['#150800', '#cc5500', '#ff6a00'],
    colors: {
      'titleBar.activeBackground':        '#150800',
      'titleBar.activeForeground':        '#ff6a00',
      'titleBar.inactiveBackground':      '#0f0500',
      'titleBar.inactiveForeground':      '#cc4400',
      'titleBar.border':                  '#cc5500',
      'activityBar.background':           '#150800',
      'activityBar.foreground':           '#ff6a00',
      'activityBar.inactiveForeground':   '#663300',
      'activityBar.border':               '#aa4400',
      'activityBarBadge.background':      '#ff6a00',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#3d1a00',
      'statusBar.foreground':             '#ff6a00',
      'statusBar.border':                 '#cc5500',
      'statusBarItem.hoverBackground':    '#5c2600',
      'sideBar.background':               '#1a0a00',
      'sideBar.foreground':               '#ffddaa',
      'sideBar.border':                   '#aa4400',
      'sideBarTitle.foreground':          '#ff6a00',
      'sideBarSectionHeader.background':  '#0f0500',
      'sideBarSectionHeader.foreground':  '#ff6a00',
      'editorGroupHeader.tabsBackground': '#150800',
      'tab.activeBackground':             '#2e1200',
      'tab.activeForeground':             '#ff6a00',
      'tab.activeBorder':                 '#ff6a00',
      'tab.inactiveBackground':           '#1a0a00',
      'tab.inactiveForeground':           '#995500',
      'focusBorder':                      '#ff6a00',
      'selection.background':             '#ff6a0033',
      'menu.background':                  '#1a0a00',
      'menu.foreground':                  '#ffddaa',
      'menu.selectionBackground':         '#3d1a00',
      'menu.selectionForeground':         '#ff6a00',
      'menubar.selectionBackground':      '#3d1a00',
      'menubar.selectionForeground':      '#ff6a00',
      'panel.background':                 '#1a0a00',
      'panel.border':                     '#aa4400',
      'panelTitle.activeForeground':      '#ff6a00',
      'panelTitle.activeBorder':          '#ff6a00',
      'scrollbarSlider.background':       '#ff6a0030',
      'scrollbarSlider.hoverBackground':  '#ff6a0055',
    },
  },

  {
    name: 'Blood Red', type: 'dark', indicator: 'RD', accent: '#ff1a4d',
    preview: ['#150005', '#cc003a', '#ff1a4d'],
    colors: {
      'titleBar.activeBackground':        '#150005',
      'titleBar.activeForeground':        '#ff1a4d',
      'titleBar.inactiveBackground':      '#0f0003',
      'titleBar.inactiveForeground':      '#cc0035',
      'titleBar.border':                  '#aa0030',
      'activityBar.background':           '#150005',
      'activityBar.foreground':           '#ff1a4d',
      'activityBar.inactiveForeground':   '#770022',
      'activityBar.border':               '#880025',
      'activityBarBadge.background':      '#ff1a4d',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#400015',
      'statusBar.foreground':             '#ff1a4d',
      'statusBar.border':                 '#cc003a',
      'statusBarItem.hoverBackground':    '#5c0020',
      'sideBar.background':               '#1f000a',
      'sideBar.foreground':               '#ffaabb',
      'sideBar.border':                   '#880025',
      'sideBarTitle.foreground':          '#ff1a4d',
      'sideBarSectionHeader.background':  '#0f0003',
      'sideBarSectionHeader.foreground':  '#ff1a4d',
      'editorGroupHeader.tabsBackground': '#150005',
      'tab.activeBackground':             '#300010',
      'tab.activeForeground':             '#ff1a4d',
      'tab.activeBorder':                 '#ff1a4d',
      'tab.inactiveBackground':           '#1f000a',
      'tab.inactiveForeground':           '#992233',
      'focusBorder':                      '#ff1a4d',
      'selection.background':             '#ff1a4d33',
      'menu.background':                  '#1f000a',
      'menu.foreground':                  '#ffaabb',
      'menu.selectionBackground':         '#400015',
      'menu.selectionForeground':         '#ff1a4d',
      'menubar.selectionBackground':      '#400015',
      'menubar.selectionForeground':      '#ff1a4d',
      'panel.background':                 '#1f000a',
      'panel.border':                     '#880025',
      'panelTitle.activeForeground':      '#ff1a4d',
      'panelTitle.activeBorder':          '#ff1a4d',
      'scrollbarSlider.background':       '#ff1a4d30',
      'scrollbarSlider.hoverBackground':  '#ff1a4d55',
    },
  },

  {
    name: 'Obsidian', type: 'dark', indicator: 'OB', accent: '#c0c0e0',
    preview: ['#080810', '#505070', '#c0c0e0'],
    colors: {
      'titleBar.activeBackground':        '#080810',
      'titleBar.activeForeground':        '#c0c0e0',
      'titleBar.inactiveBackground':      '#040408',
      'titleBar.inactiveForeground':      '#8080a0',
      'titleBar.border':                  '#404060',
      'activityBar.background':           '#080810',
      'activityBar.foreground':           '#c0c0e0',
      'activityBar.inactiveForeground':   '#404055',
      'activityBar.border':               '#303050',
      'activityBarBadge.background':      '#c0c0e0',
      'activityBarBadge.foreground':      '#080810',
      'statusBar.background':             '#14141e',
      'statusBar.foreground':             '#c0c0e0',
      'statusBar.border':                 '#404060',
      'statusBarItem.hoverBackground':    '#20202e',
      'sideBar.background':               '#0d0d18',
      'sideBar.foreground':               '#d0d0e8',
      'sideBar.border':                   '#303050',
      'sideBarTitle.foreground':          '#c0c0e0',
      'sideBarSectionHeader.background':  '#040408',
      'sideBarSectionHeader.foreground':  '#c0c0e0',
      'editorGroupHeader.tabsBackground': '#080810',
      'tab.activeBackground':             '#181828',
      'tab.activeForeground':             '#c0c0e0',
      'tab.activeBorder':                 '#c0c0e0',
      'tab.inactiveBackground':           '#0d0d18',
      'tab.inactiveForeground':           '#707090',
      'focusBorder':                      '#c0c0e0',
      'selection.background':             '#c0c0e033',
      'menu.background':                  '#0d0d18',
      'menu.foreground':                  '#d0d0e8',
      'menu.selectionBackground':         '#14141e',
      'menu.selectionForeground':         '#c0c0e0',
      'menubar.selectionBackground':      '#14141e',
      'menubar.selectionForeground':      '#c0c0e0',
      'panel.background':                 '#0d0d18',
      'panel.border':                     '#303050',
      'panelTitle.activeForeground':      '#c0c0e0',
      'panelTitle.activeBorder':          '#c0c0e0',
      'scrollbarSlider.background':       '#c0c0e030',
      'scrollbarSlider.hoverBackground':  '#c0c0e055',
    },
  },

  {
    name: 'Deep Navy', type: 'dark', indicator: 'NV', accent: '#4488ff',
    preview: ['#00040f', '#2255cc', '#4488ff'],
    colors: {
      'titleBar.activeBackground':        '#00040f',
      'titleBar.activeForeground':        '#4488ff',
      'titleBar.inactiveBackground':      '#000208',
      'titleBar.inactiveForeground':      '#2266cc',
      'titleBar.border':                  '#1133aa',
      'activityBar.background':           '#00040f',
      'activityBar.foreground':           '#4488ff',
      'activityBar.inactiveForeground':   '#112266',
      'activityBar.border':               '#0f2288',
      'activityBarBadge.background':      '#4488ff',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#001540',
      'statusBar.foreground':             '#4488ff',
      'statusBar.border':                 '#2255cc',
      'statusBarItem.hoverBackground':    '#002060',
      'sideBar.background':               '#000918',
      'sideBar.foreground':               '#aabbff',
      'sideBar.border':                   '#0f2288',
      'sideBarTitle.foreground':          '#4488ff',
      'sideBarSectionHeader.background':  '#000208',
      'sideBarSectionHeader.foreground':  '#4488ff',
      'editorGroupHeader.tabsBackground': '#00040f',
      'tab.activeBackground':             '#001030',
      'tab.activeForeground':             '#4488ff',
      'tab.activeBorder':                 '#4488ff',
      'tab.inactiveBackground':           '#000918',
      'tab.inactiveForeground':           '#336699',
      'focusBorder':                      '#4488ff',
      'selection.background':             '#4488ff33',
      'menu.background':                  '#000918',
      'menu.foreground':                  '#aabbff',
      'menu.selectionBackground':         '#001540',
      'menu.selectionForeground':         '#4488ff',
      'menubar.selectionBackground':      '#001540',
      'menubar.selectionForeground':      '#4488ff',
      'panel.background':                 '#000918',
      'panel.border':                     '#0f2288',
      'panelTitle.activeForeground':      '#4488ff',
      'panelTitle.activeBorder':          '#4488ff',
      'scrollbarSlider.background':       '#4488ff30',
      'scrollbarSlider.hoverBackground':  '#4488ff55',
    },
  },

  {
    name: 'Hot Pink', type: 'dark', indicator: 'HP', accent: '#ff0090',
    preview: ['#150010', '#cc0070', '#ff0090'],
    colors: {
      'titleBar.activeBackground':        '#150010',
      'titleBar.activeForeground':        '#ff0090',
      'titleBar.inactiveBackground':      '#0f000a',
      'titleBar.inactiveForeground':      '#cc0070',
      'titleBar.border':                  '#aa005a',
      'activityBar.background':           '#150010',
      'activityBar.foreground':           '#ff0090',
      'activityBar.inactiveForeground':   '#770055',
      'activityBar.border':               '#880060',
      'activityBarBadge.background':      '#ff0090',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#400030',
      'statusBar.foreground':             '#ff0090',
      'statusBar.border':                 '#cc0070',
      'statusBarItem.hoverBackground':    '#5c0044',
      'sideBar.background':               '#1f0018',
      'sideBar.foreground':               '#ffaadd',
      'sideBar.border':                   '#880060',
      'sideBarTitle.foreground':          '#ff0090',
      'sideBarSectionHeader.background':  '#0f000a',
      'sideBarSectionHeader.foreground':  '#ff0090',
      'editorGroupHeader.tabsBackground': '#150010',
      'tab.activeBackground':             '#2e0024',
      'tab.activeForeground':             '#ff0090',
      'tab.activeBorder':                 '#ff0090',
      'tab.inactiveBackground':           '#1f0018',
      'tab.inactiveForeground':           '#993366',
      'focusBorder':                      '#ff0090',
      'selection.background':             '#ff009033',
      'menu.background':                  '#1f0018',
      'menu.foreground':                  '#ffaadd',
      'menu.selectionBackground':         '#400030',
      'menu.selectionForeground':         '#ff0090',
      'menubar.selectionBackground':      '#400030',
      'menubar.selectionForeground':      '#ff0090',
      'panel.background':                 '#1f0018',
      'panel.border':                     '#880060',
      'panelTitle.activeForeground':      '#ff0090',
      'panelTitle.activeBorder':          '#ff0090',
      'scrollbarSlider.background':       '#ff009030',
      'scrollbarSlider.hoverBackground':  '#ff009055',
    },
  },

  {
    name: 'Neon Yellow', type: 'dark', indicator: 'NY', accent: '#f0d000',
    preview: ['#141200', '#c0a800', '#f0d000'],
    colors: {
      'titleBar.activeBackground':        '#141200',
      'titleBar.activeForeground':        '#f0d000',
      'titleBar.inactiveBackground':      '#0e0c00',
      'titleBar.inactiveForeground':      '#c0a800',
      'titleBar.border':                  '#998800',
      'activityBar.background':           '#141200',
      'activityBar.foreground':           '#f0d000',
      'activityBar.inactiveForeground':   '#666600',
      'activityBar.border':               '#887700',
      'activityBarBadge.background':      '#f0d000',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#3d3300',
      'statusBar.foreground':             '#f0d000',
      'statusBar.border':                 '#c0a800',
      'statusBarItem.hoverBackground':    '#5c4e00',
      'sideBar.background':               '#1e1a00',
      'sideBar.foreground':               '#fff5aa',
      'sideBar.border':                   '#887700',
      'sideBarTitle.foreground':          '#f0d000',
      'sideBarSectionHeader.background':  '#0e0c00',
      'sideBarSectionHeader.foreground':  '#f0d000',
      'editorGroupHeader.tabsBackground': '#141200',
      'tab.activeBackground':             '#2e2800',
      'tab.activeForeground':             '#f0d000',
      'tab.activeBorder':                 '#f0d000',
      'tab.inactiveBackground':           '#1e1a00',
      'tab.inactiveForeground':           '#998800',
      'focusBorder':                      '#f0d000',
      'selection.background':             '#f0d00033',
      'menu.background':                  '#1e1a00',
      'menu.foreground':                  '#fff5aa',
      'menu.selectionBackground':         '#3d3300',
      'menu.selectionForeground':         '#f0d000',
      'menubar.selectionBackground':      '#3d3300',
      'menubar.selectionForeground':      '#f0d000',
      'panel.background':                 '#1e1a00',
      'panel.border':                     '#887700',
      'panelTitle.activeForeground':      '#f0d000',
      'panelTitle.activeBorder':          '#f0d000',
      'scrollbarSlider.background':       '#f0d00030',
      'scrollbarSlider.hoverBackground':  '#f0d00055',
    },
  },

  {
    name: 'Steel Gray', type: 'dark', indicator: 'SG', accent: '#8899bb',
    preview: ['#0a0d12', '#607080', '#8899bb'],
    colors: {
      'titleBar.activeBackground':        '#0a0d12',
      'titleBar.activeForeground':        '#8899bb',
      'titleBar.inactiveBackground':      '#06080d',
      'titleBar.inactiveForeground':      '#607080',
      'titleBar.border':                  '#445566',
      'activityBar.background':           '#0a0d12',
      'activityBar.foreground':           '#8899bb',
      'activityBar.inactiveForeground':   '#334455',
      'activityBar.border':               '#334466',
      'activityBarBadge.background':      '#8899bb',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#1c2230',
      'statusBar.foreground':             '#8899bb',
      'statusBar.border':                 '#607080',
      'statusBarItem.hoverBackground':    '#263040',
      'sideBar.background':               '#101520',
      'sideBar.foreground':               '#c8d4e8',
      'sideBar.border':                   '#334466',
      'sideBarTitle.foreground':          '#8899bb',
      'sideBarSectionHeader.background':  '#06080d',
      'sideBarSectionHeader.foreground':  '#8899bb',
      'editorGroupHeader.tabsBackground': '#0a0d12',
      'tab.activeBackground':             '#1c2430',
      'tab.activeForeground':             '#8899bb',
      'tab.activeBorder':                 '#8899bb',
      'tab.inactiveBackground':           '#101520',
      'tab.inactiveForeground':           '#556677',
      'focusBorder':                      '#8899bb',
      'selection.background':             '#8899bb33',
      'menu.background':                  '#101520',
      'menu.foreground':                  '#c8d4e8',
      'menu.selectionBackground':         '#1c2230',
      'menu.selectionForeground':         '#8899bb',
      'menubar.selectionBackground':      '#1c2230',
      'menubar.selectionForeground':      '#8899bb',
      'panel.background':                 '#101520',
      'panel.border':                     '#334466',
      'panelTitle.activeForeground':      '#8899bb',
      'panelTitle.activeBorder':          '#8899bb',
      'scrollbarSlider.background':       '#8899bb30',
      'scrollbarSlider.hoverBackground':  '#8899bb55',
    },
  },

  {
    name: 'Amber Glow', type: 'dark', indicator: 'AG', accent: '#ffaa00',
    preview: ['#140c00', '#cc8800', '#ffaa00'],
    colors: {
      'titleBar.activeBackground':        '#140c00',
      'titleBar.activeForeground':        '#ffaa00',
      'titleBar.inactiveBackground':      '#0e0800',
      'titleBar.inactiveForeground':      '#cc8800',
      'titleBar.border':                  '#aa6600',
      'activityBar.background':           '#140c00',
      'activityBar.foreground':           '#ffaa00',
      'activityBar.inactiveForeground':   '#775500',
      'activityBar.border':               '#996600',
      'activityBarBadge.background':      '#ffaa00',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#3d2800',
      'statusBar.foreground':             '#ffaa00',
      'statusBar.border':                 '#cc8800',
      'statusBarItem.hoverBackground':    '#5c3c00',
      'sideBar.background':               '#1e1200',
      'sideBar.foreground':               '#ffd888',
      'sideBar.border':                   '#996600',
      'sideBarTitle.foreground':          '#ffaa00',
      'sideBarSectionHeader.background':  '#0e0800',
      'sideBarSectionHeader.foreground':  '#ffaa00',
      'editorGroupHeader.tabsBackground': '#140c00',
      'tab.activeBackground':             '#2e1e00',
      'tab.activeForeground':             '#ffaa00',
      'tab.activeBorder':                 '#ffaa00',
      'tab.inactiveBackground':           '#1e1200',
      'tab.inactiveForeground':           '#996600',
      'focusBorder':                      '#ffaa00',
      'selection.background':             '#ffaa0033',
      'menu.background':                  '#1e1200',
      'menu.foreground':                  '#ffd888',
      'menu.selectionBackground':         '#3d2800',
      'menu.selectionForeground':         '#ffaa00',
      'menubar.selectionBackground':      '#3d2800',
      'menubar.selectionForeground':      '#ffaa00',
      'panel.background':                 '#1e1200',
      'panel.border':                     '#996600',
      'panelTitle.activeForeground':      '#ffaa00',
      'panelTitle.activeBorder':          '#ffaa00',
      'scrollbarSlider.background':       '#ffaa0030',
      'scrollbarSlider.hoverBackground':  '#ffaa0055',
    },
  },

  {
    name: 'Crimson', type: 'dark', indicator: 'CR', accent: '#dd1133',
    preview: ['#120005', '#bb0025', '#dd1133'],
    colors: {
      'titleBar.activeBackground':        '#120005',
      'titleBar.activeForeground':        '#dd1133',
      'titleBar.inactiveBackground':      '#0c0003',
      'titleBar.inactiveForeground':      '#bb0025',
      'titleBar.border':                  '#880020',
      'activityBar.background':           '#120005',
      'activityBar.foreground':           '#dd1133',
      'activityBar.inactiveForeground':   '#660015',
      'activityBar.border':               '#770020',
      'activityBarBadge.background':      '#dd1133',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#380015',
      'statusBar.foreground':             '#dd1133',
      'statusBar.border':                 '#bb0025',
      'statusBarItem.hoverBackground':    '#520020',
      'sideBar.background':               '#1c000a',
      'sideBar.foreground':               '#ffbbcc',
      'sideBar.border':                   '#770020',
      'sideBarTitle.foreground':          '#dd1133',
      'sideBarSectionHeader.background':  '#0c0003',
      'sideBarSectionHeader.foreground':  '#dd1133',
      'editorGroupHeader.tabsBackground': '#120005',
      'tab.activeBackground':             '#2a0010',
      'tab.activeForeground':             '#dd1133',
      'tab.activeBorder':                 '#dd1133',
      'tab.inactiveBackground':           '#1c000a',
      'tab.inactiveForeground':           '#882233',
      'focusBorder':                      '#dd1133',
      'selection.background':             '#dd113333',
      'menu.background':                  '#1c000a',
      'menu.foreground':                  '#ffbbcc',
      'menu.selectionBackground':         '#380015',
      'menu.selectionForeground':         '#dd1133',
      'menubar.selectionBackground':      '#380015',
      'menubar.selectionForeground':      '#dd1133',
      'panel.background':                 '#1c000a',
      'panel.border':                     '#770020',
      'panelTitle.activeForeground':      '#dd1133',
      'panelTitle.activeBorder':          '#dd1133',
      'scrollbarSlider.background':       '#dd113330',
      'scrollbarSlider.hoverBackground':  '#dd113355',
    },
  },

  {
    name: 'Bourbon Brown', type: 'dark', indicator: 'BB', accent: '#d4783e',
    preview: ['#150a00', '#a85820', '#d4783e'],
    colors: {
      'titleBar.activeBackground':        '#150a00',
      'titleBar.activeForeground':        '#d4783e',
      'titleBar.inactiveBackground':      '#0f0600',
      'titleBar.inactiveForeground':      '#a85820',
      'titleBar.border':                  '#7a3e10',
      'activityBar.background':           '#150a00',
      'activityBar.foreground':           '#d4783e',
      'activityBar.inactiveForeground':   '#6e3010',
      'activityBar.border':               '#6a3810',
      'activityBarBadge.background':      '#d4783e',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#3d2200',
      'statusBar.foreground':             '#d4783e',
      'statusBar.border':                 '#a85820',
      'statusBarItem.hoverBackground':    '#5c3400',
      'sideBar.background':               '#1f1000',
      'sideBar.foreground':               '#f5d0a0',
      'sideBar.border':                   '#6a3810',
      'sideBarTitle.foreground':          '#d4783e',
      'sideBarSectionHeader.background':  '#0f0600',
      'sideBarSectionHeader.foreground':  '#d4783e',
      'editorGroupHeader.tabsBackground': '#150a00',
      'tab.activeBackground':             '#2e1800',
      'tab.activeForeground':             '#d4783e',
      'tab.activeBorder':                 '#d4783e',
      'tab.inactiveBackground':           '#1f1000',
      'tab.inactiveForeground':           '#8c5030',
      'focusBorder':                      '#d4783e',
      'selection.background':             '#d4783e33',
      'menu.background':                  '#1f1000',
      'menu.foreground':                  '#f5d0a0',
      'menu.selectionBackground':         '#3d2200',
      'menu.selectionForeground':         '#d4783e',
      'menubar.selectionBackground':      '#3d2200',
      'menubar.selectionForeground':      '#d4783e',
      'panel.background':                 '#1f1000',
      'panel.border':                     '#6a3810',
      'panelTitle.activeForeground':      '#d4783e',
      'panelTitle.activeBorder':          '#d4783e',
      'scrollbarSlider.background':       '#d4783e30',
      'scrollbarSlider.hoverBackground':  '#d4783e55',
    },
  },

  {
    name: 'Midnight Blue', type: 'dark', indicator: 'MB', accent: '#3355ee',
    preview: ['#00000f', '#2244cc', '#3355ee'],
    colors: {
      'titleBar.activeBackground':        '#00000f',
      'titleBar.activeForeground':        '#3355ee',
      'titleBar.inactiveBackground':      '#000008',
      'titleBar.inactiveForeground':      '#2244cc',
      'titleBar.border':                  '#111888',
      'activityBar.background':           '#00000f',
      'activityBar.foreground':           '#3355ee',
      'activityBar.inactiveForeground':   '#111866',
      'activityBar.border':               '#0e1677',
      'activityBarBadge.background':      '#3355ee',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#000048',
      'statusBar.foreground':             '#3355ee',
      'statusBar.border':                 '#2244cc',
      'statusBarItem.hoverBackground':    '#000060',
      'sideBar.background':               '#00001a',
      'sideBar.foreground':               '#99aaff',
      'sideBar.border':                   '#0e1677',
      'sideBarTitle.foreground':          '#3355ee',
      'sideBarSectionHeader.background':  '#000008',
      'sideBarSectionHeader.foreground':  '#3355ee',
      'editorGroupHeader.tabsBackground': '#00000f',
      'tab.activeBackground':             '#000030',
      'tab.activeForeground':             '#3355ee',
      'tab.activeBorder':                 '#3355ee',
      'tab.inactiveBackground':           '#00001a',
      'tab.inactiveForeground':           '#223399',
      'focusBorder':                      '#3355ee',
      'selection.background':             '#3355ee33',
      'menu.background':                  '#00001a',
      'menu.foreground':                  '#99aaff',
      'menu.selectionBackground':         '#000048',
      'menu.selectionForeground':         '#3355ee',
      'menubar.selectionBackground':      '#000048',
      'menubar.selectionForeground':      '#3355ee',
      'panel.background':                 '#00001a',
      'panel.border':                     '#0e1677',
      'panelTitle.activeForeground':      '#3355ee',
      'panelTitle.activeBorder':          '#3355ee',
      'scrollbarSlider.background':       '#3355ee30',
      'scrollbarSlider.hoverBackground':  '#3355ee55',
    },
  },

  {
    name: 'Magenta Storm', type: 'dark', indicator: 'MG', accent: '#ff00ff',
    preview: ['#150015', '#cc00cc', '#ff00ff'],
    colors: {
      'titleBar.activeBackground':        '#150015',
      'titleBar.activeForeground':        '#ff00ff',
      'titleBar.inactiveBackground':      '#0f000f',
      'titleBar.inactiveForeground':      '#cc00cc',
      'titleBar.border':                  '#990099',
      'activityBar.background':           '#150015',
      'activityBar.foreground':           '#ff00ff',
      'activityBar.inactiveForeground':   '#880088',
      'activityBar.border':               '#880088',
      'activityBarBadge.background':      '#ff00ff',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#400040',
      'statusBar.foreground':             '#ff00ff',
      'statusBar.border':                 '#cc00cc',
      'statusBarItem.hoverBackground':    '#5c005c',
      'sideBar.background':               '#1f001f',
      'sideBar.foreground':               '#ffaaff',
      'sideBar.border':                   '#880088',
      'sideBarTitle.foreground':          '#ff00ff',
      'sideBarSectionHeader.background':  '#0f000f',
      'sideBarSectionHeader.foreground':  '#ff00ff',
      'editorGroupHeader.tabsBackground': '#150015',
      'tab.activeBackground':             '#2e002e',
      'tab.activeForeground':             '#ff00ff',
      'tab.activeBorder':                 '#ff00ff',
      'tab.inactiveBackground':           '#1f001f',
      'tab.inactiveForeground':           '#993399',
      'focusBorder':                      '#ff00ff',
      'selection.background':             '#ff00ff33',
      'menu.background':                  '#1f001f',
      'menu.foreground':                  '#ffaaff',
      'menu.selectionBackground':         '#400040',
      'menu.selectionForeground':         '#ff00ff',
      'menubar.selectionBackground':      '#400040',
      'menubar.selectionForeground':      '#ff00ff',
      'panel.background':                 '#1f001f',
      'panel.border':                     '#880088',
      'panelTitle.activeForeground':      '#ff00ff',
      'panelTitle.activeBorder':          '#ff00ff',
      'scrollbarSlider.background':       '#ff00ff30',
      'scrollbarSlider.hoverBackground':  '#ff00ff55',
    },
  },

  {
    name: 'Gold Rush', type: 'dark', indicator: 'GD', accent: '#ffd700',
    preview: ['#141000', '#ccaa00', '#ffd700'],
    colors: {
      'titleBar.activeBackground':        '#141000',
      'titleBar.activeForeground':        '#ffd700',
      'titleBar.inactiveBackground':      '#0e0b00',
      'titleBar.inactiveForeground':      '#ccaa00',
      'titleBar.border':                  '#aa8800',
      'activityBar.background':           '#141000',
      'activityBar.foreground':           '#ffd700',
      'activityBar.inactiveForeground':   '#886600',
      'activityBar.border':               '#997700',
      'activityBarBadge.background':      '#ffd700',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#3d3300',
      'statusBar.foreground':             '#ffd700',
      'statusBar.border':                 '#ccaa00',
      'statusBarItem.hoverBackground':    '#5c4e00',
      'sideBar.background':               '#1e1800',
      'sideBar.foreground':               '#fff4aa',
      'sideBar.border':                   '#997700',
      'sideBarTitle.foreground':          '#ffd700',
      'sideBarSectionHeader.background':  '#0e0b00',
      'sideBarSectionHeader.foreground':  '#ffd700',
      'editorGroupHeader.tabsBackground': '#141000',
      'tab.activeBackground':             '#2e2600',
      'tab.activeForeground':             '#ffd700',
      'tab.activeBorder':                 '#ffd700',
      'tab.inactiveBackground':           '#1e1800',
      'tab.inactiveForeground':           '#998800',
      'focusBorder':                      '#ffd700',
      'selection.background':             '#ffd70033',
      'menu.background':                  '#1e1800',
      'menu.foreground':                  '#fff4aa',
      'menu.selectionBackground':         '#3d3300',
      'menu.selectionForeground':         '#ffd700',
      'menubar.selectionBackground':      '#3d3300',
      'menubar.selectionForeground':      '#ffd700',
      'panel.background':                 '#1e1800',
      'panel.border':                     '#997700',
      'panelTitle.activeForeground':      '#ffd700',
      'panelTitle.activeBorder':          '#ffd700',
      'scrollbarSlider.background':       '#ffd70030',
      'scrollbarSlider.hoverBackground':  '#ffd70055',
    },
  },

  {
    name: 'Ash Gray', type: 'dark', indicator: 'AS', accent: '#7b8fa0',
    preview: ['#101214', '#566070', '#7b8fa0'],
    colors: {
      'titleBar.activeBackground':        '#101214',
      'titleBar.activeForeground':        '#7b8fa0',
      'titleBar.inactiveBackground':      '#0a0c0e',
      'titleBar.inactiveForeground':      '#566070',
      'titleBar.border':                  '#3a4a58',
      'activityBar.background':           '#101214',
      'activityBar.foreground':           '#7b8fa0',
      'activityBar.inactiveForeground':   '#334455',
      'activityBar.border':               '#2a3a48',
      'activityBarBadge.background':      '#7b8fa0',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#222830',
      'statusBar.foreground':             '#7b8fa0',
      'statusBar.border':                 '#566070',
      'statusBarItem.hoverBackground':    '#2e3640',
      'sideBar.background':               '#181c20',
      'sideBar.foreground':               '#b8c8d8',
      'sideBar.border':                   '#2a3a48',
      'sideBarTitle.foreground':          '#7b8fa0',
      'sideBarSectionHeader.background':  '#0a0c0e',
      'sideBarSectionHeader.foreground':  '#7b8fa0',
      'editorGroupHeader.tabsBackground': '#101214',
      'tab.activeBackground':             '#202830',
      'tab.activeForeground':             '#7b8fa0',
      'tab.activeBorder':                 '#7b8fa0',
      'tab.inactiveBackground':           '#181c20',
      'tab.inactiveForeground':           '#556677',
      'focusBorder':                      '#7b8fa0',
      'selection.background':             '#7b8fa033',
      'menu.background':                  '#181c20',
      'menu.foreground':                  '#b8c8d8',
      'menu.selectionBackground':         '#222830',
      'menu.selectionForeground':         '#7b8fa0',
      'menubar.selectionBackground':      '#222830',
      'menubar.selectionForeground':      '#7b8fa0',
      'panel.background':                 '#181c20',
      'panel.border':                     '#2a3a48',
      'panelTitle.activeForeground':      '#7b8fa0',
      'panelTitle.activeBorder':          '#7b8fa0',
      'scrollbarSlider.background':       '#7b8fa030',
      'scrollbarSlider.hoverBackground':  '#7b8fa055',
    },
  },

  {
    name: 'Rust Metal', type: 'dark', indicator: 'RM', accent: '#cc5511',
    preview: ['#140800', '#aa4408', '#cc5511'],
    colors: {
      'titleBar.activeBackground':        '#140800',
      'titleBar.activeForeground':        '#cc5511',
      'titleBar.inactiveBackground':      '#0e0500',
      'titleBar.inactiveForeground':      '#aa4408',
      'titleBar.border':                  '#883300',
      'activityBar.background':           '#140800',
      'activityBar.foreground':           '#cc5511',
      'activityBar.inactiveForeground':   '#6e2500',
      'activityBar.border':               '#772e00',
      'activityBarBadge.background':      '#cc5511',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#3d2200',
      'statusBar.foreground':             '#cc5511',
      'statusBar.border':                 '#aa4408',
      'statusBarItem.hoverBackground':    '#5c3400',
      'sideBar.background':               '#1e0f00',
      'sideBar.foreground':               '#f5c090',
      'sideBar.border':                   '#772e00',
      'sideBarTitle.foreground':          '#cc5511',
      'sideBarSectionHeader.background':  '#0e0500',
      'sideBarSectionHeader.foreground':  '#cc5511',
      'editorGroupHeader.tabsBackground': '#140800',
      'tab.activeBackground':             '#2e1800',
      'tab.activeForeground':             '#cc5511',
      'tab.activeBorder':                 '#cc5511',
      'tab.inactiveBackground':           '#1e0f00',
      'tab.inactiveForeground':           '#884422',
      'focusBorder':                      '#cc5511',
      'selection.background':             '#cc551133',
      'menu.background':                  '#1e0f00',
      'menu.foreground':                  '#f5c090',
      'menu.selectionBackground':         '#3d2200',
      'menu.selectionForeground':         '#cc5511',
      'menubar.selectionBackground':      '#3d2200',
      'menubar.selectionForeground':      '#cc5511',
      'panel.background':                 '#1e0f00',
      'panel.border':                     '#772e00',
      'panelTitle.activeForeground':      '#cc5511',
      'panelTitle.activeBorder':          '#cc5511',
      'scrollbarSlider.background':       '#cc551130',
      'scrollbarSlider.hoverBackground':  '#cc551155',
    },
  },

  {
    name: 'Coral Fire', type: 'dark', indicator: 'CF', accent: '#ff5252',
    preview: ['#150a0a', '#ee3333', '#ff5252'],
    colors: {
      'titleBar.activeBackground':        '#150a0a',
      'titleBar.activeForeground':        '#ff5252',
      'titleBar.inactiveBackground':      '#0f0606',
      'titleBar.inactiveForeground':      '#ee3333',
      'titleBar.border':                  '#cc2222',
      'activityBar.background':           '#150a0a',
      'activityBar.foreground':           '#ff5252',
      'activityBar.inactiveForeground':   '#882222',
      'activityBar.border':               '#bb2222',
      'activityBarBadge.background':      '#ff5252',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#3d2222',
      'statusBar.foreground':             '#ff5252',
      'statusBar.border':                 '#ee3333',
      'statusBarItem.hoverBackground':    '#5c3030',
      'sideBar.background':               '#1f1212',
      'sideBar.foreground':               '#ffcccc',
      'sideBar.border':                   '#bb2222',
      'sideBarTitle.foreground':          '#ff5252',
      'sideBarSectionHeader.background':  '#0f0606',
      'sideBarSectionHeader.foreground':  '#ff5252',
      'editorGroupHeader.tabsBackground': '#150a0a',
      'tab.activeBackground':             '#2e1a1a',
      'tab.activeForeground':             '#ff5252',
      'tab.activeBorder':                 '#ff5252',
      'tab.inactiveBackground':           '#1f1212',
      'tab.inactiveForeground':           '#993333',
      'focusBorder':                      '#ff5252',
      'selection.background':             '#ff525233',
      'menu.background':                  '#1f1212',
      'menu.foreground':                  '#ffcccc',
      'menu.selectionBackground':         '#3d2222',
      'menu.selectionForeground':         '#ff5252',
      'menubar.selectionBackground':      '#3d2222',
      'menubar.selectionForeground':      '#ff5252',
      'panel.background':                 '#1f1212',
      'panel.border':                     '#bb2222',
      'panelTitle.activeForeground':      '#ff5252',
      'panelTitle.activeBorder':          '#ff5252',
      'scrollbarSlider.background':       '#ff525230',
      'scrollbarSlider.hoverBackground':  '#ff525255',
    },
  },

  {
    name: 'Cyber Teal', type: 'dark', indicator: 'CT', accent: '#00ffcc',
    preview: ['#001a14', '#00ccaa', '#00ffcc'],
    colors: {
      'titleBar.activeBackground':        '#001a14',
      'titleBar.activeForeground':        '#00ffcc',
      'titleBar.inactiveBackground':      '#00100c',
      'titleBar.inactiveForeground':      '#00ccaa',
      'titleBar.border':                  '#008866',
      'activityBar.background':           '#001a14',
      'activityBar.foreground':           '#00ffcc',
      'activityBar.inactiveForeground':   '#006644',
      'activityBar.border':               '#007755',
      'activityBarBadge.background':      '#00ffcc',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#004a38',
      'statusBar.foreground':             '#00ffcc',
      'statusBar.border':                 '#00ccaa',
      'statusBarItem.hoverBackground':    '#006650',
      'sideBar.background':               '#00241e',
      'sideBar.foreground':               '#aaffee',
      'sideBar.border':                   '#007755',
      'sideBarTitle.foreground':          '#00ffcc',
      'sideBarSectionHeader.background':  '#00100c',
      'sideBarSectionHeader.foreground':  '#00ffcc',
      'editorGroupHeader.tabsBackground': '#001a14',
      'tab.activeBackground':             '#003828',
      'tab.activeForeground':             '#00ffcc',
      'tab.activeBorder':                 '#00ffcc',
      'tab.inactiveBackground':           '#00241e',
      'tab.inactiveForeground':           '#009977',
      'focusBorder':                      '#00ffcc',
      'selection.background':             '#00ffcc33',
      'menu.background':                  '#00241e',
      'menu.foreground':                  '#aaffee',
      'menu.selectionBackground':         '#004a38',
      'menu.selectionForeground':         '#00ffcc',
      'menubar.selectionBackground':      '#004a38',
      'menubar.selectionForeground':      '#00ffcc',
      'panel.background':                 '#00241e',
      'panel.border':                     '#007755',
      'panelTitle.activeForeground':      '#00ffcc',
      'panelTitle.activeBorder':          '#00ffcc',
      'scrollbarSlider.background':       '#00ffcc30',
      'scrollbarSlider.hoverBackground':  '#00ffcc55',
    },
  },

  {
    name: 'Lava Red', type: 'dark', indicator: 'LV', accent: '#ff3300',
    preview: ['#150300', '#dd2200', '#ff3300'],
    colors: {
      'titleBar.activeBackground':        '#150300',
      'titleBar.activeForeground':        '#ff3300',
      'titleBar.inactiveBackground':      '#0f0200',
      'titleBar.inactiveForeground':      '#dd2200',
      'titleBar.border':                  '#aa1a00',
      'activityBar.background':           '#150300',
      'activityBar.foreground':           '#ff3300',
      'activityBar.inactiveForeground':   '#882200',
      'activityBar.border':               '#991a00',
      'activityBarBadge.background':      '#ff3300',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#3d1000',
      'statusBar.foreground':             '#ff3300',
      'statusBar.border':                 '#dd2200',
      'statusBarItem.hoverBackground':    '#5c1800',
      'sideBar.background':               '#1f0500',
      'sideBar.foreground':               '#ffccaa',
      'sideBar.border':                   '#991a00',
      'sideBarTitle.foreground':          '#ff3300',
      'sideBarSectionHeader.background':  '#0f0200',
      'sideBarSectionHeader.foreground':  '#ff3300',
      'editorGroupHeader.tabsBackground': '#150300',
      'tab.activeBackground':             '#2e0a00',
      'tab.activeForeground':             '#ff3300',
      'tab.activeBorder':                 '#ff3300',
      'tab.inactiveBackground':           '#1f0500',
      'tab.inactiveForeground':           '#993322',
      'focusBorder':                      '#ff3300',
      'selection.background':             '#ff330033',
      'menu.background':                  '#1f0500',
      'menu.foreground':                  '#ffccaa',
      'menu.selectionBackground':         '#3d1000',
      'menu.selectionForeground':         '#ff3300',
      'menubar.selectionBackground':      '#3d1000',
      'menubar.selectionForeground':      '#ff3300',
      'panel.background':                 '#1f0500',
      'panel.border':                     '#991a00',
      'panelTitle.activeForeground':      '#ff3300',
      'panelTitle.activeBorder':          '#ff3300',
      'scrollbarSlider.background':       '#ff330030',
      'scrollbarSlider.hoverBackground':  '#ff330055',
    },
  },

  {
    name: 'Galaxy Purple', type: 'dark', indicator: 'GP', accent: '#aa44ff',
    preview: ['#0a0020', '#8822ee', '#aa44ff'],
    colors: {
      'titleBar.activeBackground':        '#0a0020',
      'titleBar.activeForeground':        '#aa44ff',
      'titleBar.inactiveBackground':      '#060015',
      'titleBar.inactiveForeground':      '#8822ee',
      'titleBar.border':                  '#550099',
      'activityBar.background':           '#0a0020',
      'activityBar.foreground':           '#aa44ff',
      'activityBar.inactiveForeground':   '#550099',
      'activityBar.border':               '#4400aa',
      'activityBarBadge.background':      '#aa44ff',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#22005a',
      'statusBar.foreground':             '#aa44ff',
      'statusBar.border':                 '#8822ee',
      'statusBarItem.hoverBackground':    '#330077',
      'sideBar.background':               '#10002e',
      'sideBar.foreground':               '#ddaaff',
      'sideBar.border':                   '#4400aa',
      'sideBarTitle.foreground':          '#aa44ff',
      'sideBarSectionHeader.background':  '#060015',
      'sideBarSectionHeader.foreground':  '#aa44ff',
      'editorGroupHeader.tabsBackground': '#0a0020',
      'tab.activeBackground':             '#1a0040',
      'tab.activeForeground':             '#aa44ff',
      'tab.activeBorder':                 '#aa44ff',
      'tab.inactiveBackground':           '#10002e',
      'tab.inactiveForeground':           '#7733bb',
      'focusBorder':                      '#aa44ff',
      'selection.background':             '#aa44ff33',
      'menu.background':                  '#10002e',
      'menu.foreground':                  '#ddaaff',
      'menu.selectionBackground':         '#22005a',
      'menu.selectionForeground':         '#aa44ff',
      'menubar.selectionBackground':      '#22005a',
      'menubar.selectionForeground':      '#aa44ff',
      'panel.background':                 '#10002e',
      'panel.border':                     '#4400aa',
      'panelTitle.activeForeground':      '#aa44ff',
      'panelTitle.activeBorder':          '#aa44ff',
      'scrollbarSlider.background':       '#aa44ff30',
      'scrollbarSlider.hoverBackground':  '#aa44ff55',
    },
  },

  {
    name: 'Rose Neon', type: 'dark', indicator: 'RN', accent: '#ff44aa',
    preview: ['#150010', '#ee2288', '#ff44aa'],
    colors: {
      'titleBar.activeBackground':        '#150010',
      'titleBar.activeForeground':        '#ff44aa',
      'titleBar.inactiveBackground':      '#0f000a',
      'titleBar.inactiveForeground':      '#ee2288',
      'titleBar.border':                  '#bb0066',
      'activityBar.background':           '#150010',
      'activityBar.foreground':           '#ff44aa',
      'activityBar.inactiveForeground':   '#880055',
      'activityBar.border':               '#aa0066',
      'activityBarBadge.background':      '#ff44aa',
      'activityBarBadge.foreground':      '#000000',
      'statusBar.background':             '#3d0035',
      'statusBar.foreground':             '#ff44aa',
      'statusBar.border':                 '#ee2288',
      'statusBarItem.hoverBackground':    '#5c004e',
      'sideBar.background':               '#1f0018',
      'sideBar.foreground':               '#ffbbdd',
      'sideBar.border':                   '#aa0066',
      'sideBarTitle.foreground':          '#ff44aa',
      'sideBarSectionHeader.background':  '#0f000a',
      'sideBarSectionHeader.foreground':  '#ff44aa',
      'editorGroupHeader.tabsBackground': '#150010',
      'tab.activeBackground':             '#2e0028',
      'tab.activeForeground':             '#ff44aa',
      'tab.activeBorder':                 '#ff44aa',
      'tab.inactiveBackground':           '#1f0018',
      'tab.inactiveForeground':           '#993366',
      'focusBorder':                      '#ff44aa',
      'selection.background':             '#ff44aa33',
      'menu.background':                  '#1f0018',
      'menu.foreground':                  '#ffbbdd',
      'menu.selectionBackground':         '#3d0035',
      'menu.selectionForeground':         '#ff44aa',
      'menubar.selectionBackground':      '#3d0035',
      'menubar.selectionForeground':      '#ff44aa',
      'panel.background':                 '#1f0018',
      'panel.border':                     '#aa0066',
      'panelTitle.activeForeground':      '#ff44aa',
      'panelTitle.activeBorder':          '#ff44aa',
      'scrollbarSlider.background':       '#ff44aa30',
      'scrollbarSlider.hoverBackground':  '#ff44aa55',
    },
  },

  // ── LIGHT palettes ──────────────────────────────────────────
  {
    name: 'Soft Mint', type: 'light', indicator: 'M', accent: '#15803d',
    preview: ['#dcfce7', '#86efac', '#15803d'],
    colors: {
      'titleBar.activeBackground':        '#dcfce7',
      'titleBar.activeForeground':        '#14532d',
      'titleBar.inactiveBackground':      '#f0fdf4',
      'titleBar.inactiveForeground':      '#4d7a5c',
      'titleBar.border':                  '#86efac',
      'activityBar.background':           '#dcfce7',
      'activityBar.foreground':           '#15803d',
      'activityBar.inactiveForeground':   '#6aad80',
      'activityBar.border':               '#86efac',
      'activityBarBadge.background':      '#15803d',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#bbf7d0',
      'statusBar.foreground':             '#14532d',
      'statusBar.border':                 '#86efac',
      'statusBarItem.hoverBackground':    '#a7f3d0',
      'sideBar.background':               '#f0fdf4',
      'sideBar.foreground':               '#1a3d28',
      'sideBar.border':                   '#86efac',
      'sideBarTitle.foreground':          '#15803d',
      'sideBarSectionHeader.background':  '#dcfce7',
      'sideBarSectionHeader.foreground':  '#15803d',
      'editorGroupHeader.tabsBackground': '#dcfce7',
      'tab.activeBackground':             '#bbf7d0',
      'tab.activeForeground':             '#14532d',
      'tab.activeBorder':                 '#15803d',
      'tab.inactiveBackground':           '#f0fdf4',
      'tab.inactiveForeground':           '#4d7a5c',
      'focusBorder':                      '#15803d',
      'selection.background':             '#15803d33',
      'menu.background':                  '#f0fdf4',
      'menu.foreground':                  '#1a3d28',
      'menu.selectionBackground':         '#bbf7d0',
      'menu.selectionForeground':         '#14532d',
      'menubar.selectionBackground':      '#bbf7d0',
      'menubar.selectionForeground':      '#14532d',
      'panel.background':                 '#f0fdf4',
      'panel.border':                     '#86efac',
      'panelTitle.activeForeground':      '#15803d',
      'panelTitle.activeBorder':          '#15803d',
      'scrollbarSlider.background':       '#15803d30',
      'scrollbarSlider.hoverBackground':  '#15803d55',
    },
  },

  {
    name: 'Sky Blue', type: 'light', indicator: 'S', accent: '#1d4ed8',
    preview: ['#dbeafe', '#93c5fd', '#1d4ed8'],
    colors: {
      'titleBar.activeBackground':        '#dbeafe',
      'titleBar.activeForeground':        '#1e3a8a',
      'titleBar.inactiveBackground':      '#eff6ff',
      'titleBar.inactiveForeground':      '#4d6fa8',
      'titleBar.border':                  '#93c5fd',
      'activityBar.background':           '#dbeafe',
      'activityBar.foreground':           '#1d4ed8',
      'activityBar.inactiveForeground':   '#6a8dc2',
      'activityBar.border':               '#93c5fd',
      'activityBarBadge.background':      '#1d4ed8',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#bfdbfe',
      'statusBar.foreground':             '#1e3a8a',
      'statusBar.border':                 '#93c5fd',
      'statusBarItem.hoverBackground':    '#a5c8fe',
      'sideBar.background':               '#eff6ff',
      'sideBar.foreground':               '#1a2d5c',
      'sideBar.border':                   '#93c5fd',
      'sideBarTitle.foreground':          '#1d4ed8',
      'sideBarSectionHeader.background':  '#dbeafe',
      'sideBarSectionHeader.foreground':  '#1d4ed8',
      'editorGroupHeader.tabsBackground': '#dbeafe',
      'tab.activeBackground':             '#bfdbfe',
      'tab.activeForeground':             '#1e3a8a',
      'tab.activeBorder':                 '#1d4ed8',
      'tab.inactiveBackground':           '#eff6ff',
      'tab.inactiveForeground':           '#4d6fa8',
      'focusBorder':                      '#1d4ed8',
      'selection.background':             '#1d4ed833',
      'menu.background':                  '#eff6ff',
      'menu.foreground':                  '#1a2d5c',
      'menu.selectionBackground':         '#bfdbfe',
      'menu.selectionForeground':         '#1e3a8a',
      'menubar.selectionBackground':      '#bfdbfe',
      'menubar.selectionForeground':      '#1e3a8a',
      'panel.background':                 '#eff6ff',
      'panel.border':                     '#93c5fd',
      'panelTitle.activeForeground':      '#1d4ed8',
      'panelTitle.activeBorder':          '#1d4ed8',
      'scrollbarSlider.background':       '#1d4ed830',
      'scrollbarSlider.hoverBackground':  '#1d4ed855',
    },
  },

  {
    name: 'Lavender', type: 'light', indicator: 'L', accent: '#7c3aed',
    preview: ['#ede9fe', '#c4b5fd', '#7c3aed'],
    colors: {
      'titleBar.activeBackground':        '#ede9fe',
      'titleBar.activeForeground':        '#4c1d95',
      'titleBar.inactiveBackground':      '#faf5ff',
      'titleBar.inactiveForeground':      '#6d4ea8',
      'titleBar.border':                  '#c4b5fd',
      'activityBar.background':           '#ede9fe',
      'activityBar.foreground':           '#7c3aed',
      'activityBar.inactiveForeground':   '#9b7cc2',
      'activityBar.border':               '#c4b5fd',
      'activityBarBadge.background':      '#7c3aed',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#ddd6fe',
      'statusBar.foreground':             '#4c1d95',
      'statusBar.border':                 '#c4b5fd',
      'statusBarItem.hoverBackground':    '#cbbffd',
      'sideBar.background':               '#faf5ff',
      'sideBar.foreground':               '#2e1a5c',
      'sideBar.border':                   '#c4b5fd',
      'sideBarTitle.foreground':          '#7c3aed',
      'sideBarSectionHeader.background':  '#ede9fe',
      'sideBarSectionHeader.foreground':  '#7c3aed',
      'editorGroupHeader.tabsBackground': '#ede9fe',
      'tab.activeBackground':             '#ddd6fe',
      'tab.activeForeground':             '#4c1d95',
      'tab.activeBorder':                 '#7c3aed',
      'tab.inactiveBackground':           '#faf5ff',
      'tab.inactiveForeground':           '#6d4ea8',
      'focusBorder':                      '#7c3aed',
      'selection.background':             '#7c3aed33',
      'menu.background':                  '#faf5ff',
      'menu.foreground':                  '#2e1a5c',
      'menu.selectionBackground':         '#ddd6fe',
      'menu.selectionForeground':         '#4c1d95',
      'menubar.selectionBackground':      '#ddd6fe',
      'menubar.selectionForeground':      '#4c1d95',
      'panel.background':                 '#faf5ff',
      'panel.border':                     '#c4b5fd',
      'panelTitle.activeForeground':      '#7c3aed',
      'panelTitle.activeBorder':          '#7c3aed',
      'scrollbarSlider.background':       '#7c3aed30',
      'scrollbarSlider.hoverBackground':  '#7c3aed55',
    },
  },

  {
    name: 'Sunset', type: 'light', indicator: 'U', accent: '#c2410c',
    preview: ['#fed7aa', '#fb923c', '#c2410c'],
    colors: {
      'titleBar.activeBackground':        '#fed7aa',
      'titleBar.activeForeground':        '#7c2d12',
      'titleBar.inactiveBackground':      '#fff7ed',
      'titleBar.inactiveForeground':      '#a05030',
      'titleBar.border':                  '#fb923c',
      'activityBar.background':           '#fed7aa',
      'activityBar.foreground':           '#c2410c',
      'activityBar.inactiveForeground':   '#c27a50',
      'activityBar.border':               '#fb923c',
      'activityBarBadge.background':      '#c2410c',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#fdba74',
      'statusBar.foreground':             '#7c2d12',
      'statusBar.border':                 '#fb923c',
      'statusBarItem.hoverBackground':    '#fca85a',
      'sideBar.background':               '#fff7ed',
      'sideBar.foreground':               '#431407',
      'sideBar.border':                   '#fb923c',
      'sideBarTitle.foreground':          '#c2410c',
      'sideBarSectionHeader.background':  '#fed7aa',
      'sideBarSectionHeader.foreground':  '#c2410c',
      'editorGroupHeader.tabsBackground': '#fed7aa',
      'tab.activeBackground':             '#fdba74',
      'tab.activeForeground':             '#7c2d12',
      'tab.activeBorder':                 '#c2410c',
      'tab.inactiveBackground':           '#fff7ed',
      'tab.inactiveForeground':           '#a05030',
      'focusBorder':                      '#c2410c',
      'selection.background':             '#c2410c33',
      'menu.background':                  '#fff7ed',
      'menu.foreground':                  '#431407',
      'menu.selectionBackground':         '#fdba74',
      'menu.selectionForeground':         '#7c2d12',
      'menubar.selectionBackground':      '#fdba74',
      'menubar.selectionForeground':      '#7c2d12',
      'panel.background':                 '#fff7ed',
      'panel.border':                     '#fb923c',
      'panelTitle.activeForeground':      '#c2410c',
      'panelTitle.activeBorder':          '#c2410c',
      'scrollbarSlider.background':       '#c2410c30',
      'scrollbarSlider.hoverBackground':  '#c2410c55',
    },
  },

  {
    name: 'Rose Gold', type: 'light', indicator: 'R', accent: '#be123c',
    preview: ['#fce7f3', '#f9a8d4', '#be123c'],
    colors: {
      'titleBar.activeBackground':        '#fce7f3',
      'titleBar.activeForeground':        '#881337',
      'titleBar.inactiveBackground':      '#fff1f2',
      'titleBar.inactiveForeground':      '#9d3a5a',
      'titleBar.border':                  '#f9a8d4',
      'activityBar.background':           '#fce7f3',
      'activityBar.foreground':           '#be123c',
      'activityBar.inactiveForeground':   '#c47a8a',
      'activityBar.border':               '#f9a8d4',
      'activityBarBadge.background':      '#be123c',
      'activityBarBadge.foreground':      '#ffffff',
      'statusBar.background':             '#fbcfe8',
      'statusBar.foreground':             '#881337',
      'statusBar.border':                 '#f9a8d4',
      'statusBarItem.hoverBackground':    '#f9bcd8',
      'sideBar.background':               '#fff1f2',
      'sideBar.foreground':               '#4a0a20',
      'sideBar.border':                   '#f9a8d4',
      'sideBarTitle.foreground':          '#be123c',
      'sideBarSectionHeader.background':  '#fce7f3',
      'sideBarSectionHeader.foreground':  '#be123c',
      'editorGroupHeader.tabsBackground': '#fce7f3',
      'tab.activeBackground':             '#fbcfe8',
      'tab.activeForeground':             '#881337',
      'tab.activeBorder':                 '#be123c',
      'tab.inactiveBackground':           '#fff1f2',
      'tab.inactiveForeground':           '#9d3a5a',
      'focusBorder':                      '#be123c',
      'selection.background':             '#be123c33',
      'menu.background':                  '#fff1f2',
      'menu.foreground':                  '#4a0a20',
      'menu.selectionBackground':         '#fbcfe8',
      'menu.selectionForeground':         '#881337',
      'menubar.selectionBackground':      '#fbcfe8',
      'menubar.selectionForeground':      '#881337',
      'panel.background':                 '#fff1f2',
      'panel.border':                     '#f9a8d4',
      'panelTitle.activeForeground':      '#be123c',
      'panelTitle.activeBorder':          '#be123c',
      'scrollbarSlider.background':       '#be123c30',
      'scrollbarSlider.hoverBackground':  '#be123c55',
    },
  },
];

// ── State ────────────────────────────────────────────────────────────────────

let currentIndex  = 0;
let targetIndex   = 1;
let interpStep    = 0;
let holdCounter   = 0;
let mainTimer: ReturnType<typeof setInterval> | undefined;
let themeBarItem: vscode.StatusBarItem | undefined;
let onAccentChange: ((color: string, name: string) => void) | undefined;

/*
 * Timing constants.
 *
 * We write to workbench.colorCustomizations on every tick during a transition.
 * VS Code proxies each write through its settings layer, which ultimately
 * touches disk.  Using a 160 ms tick (instead of 80 ms) halves the number of
 * disk writes per transition (10 vs 20) while still looking smooth to the eye.
 *
 *   TICK_MS       – interval between timer callbacks
 *   INTERP_STEPS  – how many ticks a cross-fade takes  (10 × 160 ms = 1.6 s)
 *   HOLD_TICKS    – how many ticks we hold each palette (15 × 160 ms = 2.4 s)
 */
const TICK_MS      = 160;
const INTERP_STEPS = 10;
const HOLD_TICKS   = 15;

// ── Public API ───────────────────────────────────────────────────────────────

export function startThemeAnimation(
  context: vscode.ExtensionContext,
  accentCallback?: (color: string, name: string) => void
): void {
  stopThemeAnimation();
  onAccentChange = accentCallback;

  if (!themeBarItem) {
    themeBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 200);
    themeBarItem.command = 'animExplorer.stopTheme';
    context.subscriptions.push(themeBarItem);
  }

  currentIndex = 0;
  targetIndex  = 1;
  interpStep   = 0;
  holdCounter  = HOLD_TICKS;

  _applyBlend(1.0);
  _updateBar();

  mainTimer = setInterval(_tick, TICK_MS);
}

export function stopThemeAnimation(): void {
  if (mainTimer) {
    clearInterval(mainTimer);
    mainTimer = undefined;
  }
  themeBarItem?.hide();
}

/** Apply a specific palette immediately (stops auto-cycle). */
export function applyPaletteByName(
  name: string,
  accentCallback?: (color: string, name: string) => void
): void {
  stopThemeAnimation();
  const idx = PALETTES.findIndex((p) => p.name === name);
  if (idx < 0) { return; }

  const palette = PALETTES[idx];
  const cfg    = vscode.workspace.getConfiguration();
  const target = vscode.workspace.workspaceFolders
    ? vscode.ConfigurationTarget.Workspace
    : vscode.ConfigurationTarget.Global;
  cfg.update('workbench.colorCustomizations', palette.colors, target);

  accentCallback?.(palette.accent, palette.name);

  if (themeBarItem) {
    themeBarItem.text    = `[${palette.indicator}] ${palette.name}`;
    themeBarItem.tooltip = `Anim Theme: ${palette.name} — click to stop`;
    themeBarItem.show();
  }
}

export function resetTheme(): void {
  stopThemeAnimation();
  const cfg    = vscode.workspace.getConfiguration();
  const target = vscode.workspace.workspaceFolders
    ? vscode.ConfigurationTarget.Workspace
    : vscode.ConfigurationTarget.Global;
  cfg.update('workbench.colorCustomizations', undefined, target);
  themeBarItem?.hide();
}

// ── Internal tick ────────────────────────────────────────────────────────────

function _tick(): void {
  if (holdCounter > 0) {
    holdCounter--;
    return;
  }

  interpStep++;
  const t = interpStep / INTERP_STEPS;
  _applyBlend(t);

  if (interpStep >= INTERP_STEPS) {
    currentIndex = targetIndex;
    targetIndex  = (targetIndex + 1) % PALETTES.length;
    interpStep   = 0;
    holdCounter  = HOLD_TICKS;
    _updateBar();
    onAccentChange?.(PALETTES[currentIndex].accent, PALETTES[currentIndex].name);
  }
}

// ── Blend & apply ────────────────────────────────────────────────────────────

function _applyBlend(t: number): void {
  const from = PALETTES[currentIndex].colors;
  const to   = PALETTES[targetIndex].colors;

  const blended: Record<string, string> = {};
  const keys = new Set([...Object.keys(from), ...Object.keys(to)]);

  for (const key of keys) {
    const a = from[key] ?? to[key];
    const b = to[key]   ?? from[key];
    blended[key] = lerpColor(a, b, t);
  }

  const cfg    = vscode.workspace.getConfiguration();
  const target = vscode.workspace.workspaceFolders
    ? vscode.ConfigurationTarget.Workspace
    : vscode.ConfigurationTarget.Global;
  cfg.update('workbench.colorCustomizations', blended, target);
}

function _updateBar(): void {
  if (!themeBarItem) { return; }
  const p = PALETTES[currentIndex];
  themeBarItem.text    = `[${p.indicator}] ${p.name}`;
  themeBarItem.tooltip = `Anim Theme: ${p.name} — click to stop`;
  themeBarItem.show();
}
